required:
  isolat: 'Gd00293-aad'
  chromosome: 'chr1001'
  path_inv_file: '/home/hugob/stage_m2/05_Inversion/output/filter_inv.tsv'

optional:
  chr_len: '4340835'
  lineage_file: ''

output:
  path_out_plot: '/home/hugob/stage_m2/06_Result_inv/plot_inv/output/{isolat}_{chromosome}_filter_invplot.png'
