required:
  isolat: 'Gd_00293-aad'
  chromosome: 'chr1001'
  path_inv_file: '/home/hugob/stage_m2/06_bench_tools_inv_calling/format_inv/output/inv_cactus_multialgn.tsv'

optional:
  chr_len: '4340835'
  lineage_file: ''

output:
  path_out_plot: '/home/hugob/stage_m2/06_bench_tools_inv_calling/plot_inv/output/{isolat}_{chromosome}_cactusmulti_invplot.png'
